src/main/java/by/epam/task5/bean/Computer.java
package by.epam.task5.bean;

import by.epam.task5.bean.type.Type;

/**
 * Created by stas- on 10/16/2015.
 */
public class Computer {
    private String id;
    private String name;
    private String origin;
    private int price;
    private Type type;

    public Type getType() {
        return type;
    }

    public void setType(Type type) {
        this.type = type;
    }

    private boolean isCritical;

    public boolean isCritical() {
        return isCritical;
    }

    public void setIsCritical(boolean isCritical) {
        this.isCritical = isCritical;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getOrigin() {
        return origin;
    }

    public void setOrigin(String origin) {
        this.origin = origin;
    }

    public int getPrice() {
        return price;
    }

    public void setPrice(int price) {
        this.price = price;
    }
}

src/main/java/by/epam/task5/bean/type/Hardware.java
package by.epam.task5.bean.type;

/**
 * Created by stas- on 10/16/2015.
 */
public class Hardware {
    private boolean hasKeyboard;
    private boolean hasMouse;
    private boolean hasSpeakers;

    public boolean isHasKeyboard() {
        return hasKeyboard;
    }

    public void setHasKeyboard(boolean hasKeyboard) {
        this.hasKeyboard = hasKeyboard;
    }

    public boolean isHasMouse() {
        return hasMouse;
    }

    public void setHasMouse(boolean hasMouse) {
        this.hasMouse = hasMouse;
    }

    public boolean isHasSpeakers() {
        return hasSpeakers;
    }

    public void setHasSpeakers(boolean hasSpeakers) {
        this.hasSpeakers = hasSpeakers;
    }
}

src/main/java/by/epam/task5/bean/type/Port.java
package by.epam.task5.bean.type;

/**
 * Created by stas- on 10/16/2015.
 */
public class Port {
    private String portName;

    public String getPortName() {
        return portName;
    }

    public void setPortName(String portName) {
        this.portName = portName;
    }
}

src/main/java/by/epam/task5/bean/type/Type.java
package by.epam.task5.bean.type;

import java.util.List;

/**
 * Created by stas- on 10/16/2015.
 */
public class Type {
    private boolean isPeripheral;
    private int power;
    private List<Port> ports;
    private Hardware hardware;

    public boolean isPeripheral() {
        return isPeripheral;
    }

    public void setIsPeripheral(boolean isPeripheral) {
        this.isPeripheral = isPeripheral;
    }

    public int getPower() {
        return power;
    }

    public void setPower(int power) {
        this.power = power;
    }

    public List<Port> getPorts() {
        return ports;
    }

    public void setPorts(List<Port> ports) {
        this.ports = ports;
    }

    public Hardware getHardware() {
        return hardware;
    }

    public void setHardware(Hardware hardware) {
        this.hardware = hardware;
    }
}

src/main/java/by/epam/task5/controller/Controller.java
package by.epam.task5.controller;

import by.epam.task5.exception.CommandException;
import by.epam.task5.logic.command.CommandHelper;
import by.epam.task5.logic.command.ICommand;
import org.apache.log4j.Logger;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.annotation.MultipartConfig;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;

@MultipartConfig
public class Controller extends HttpServlet {
    private static final Logger LOGGER = Logger.getLogger(Controller.class.getPackage().getName());
    private static final int recordsPerPage = 5;


    public Controller() {
        super();
    }

    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        String commandName = request.getParameter(RequestParameterName.COMMAND_NAME);
        ICommand command = CommandHelper.getCommand(commandName);
        String page = null;

        try {
            page = command.execute(request);
        } catch (CommandException e) {
            LOGGER.debug("Execute command failed");
            page = JspPageName.ERROR_PAGE;
            request.getRequestDispatcher(page).forward(request, response);
        }

        RequestDispatcher requestDispatcher = request.getRequestDispatcher(page);

        if (requestDispatcher != null) {
            requestDispatcher.forward(request, response);
        }

    }

    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        super.doGet(request, response);
    }

}

src/main/webapp/index.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
  <head>
    <link rel="stylesheet" href="style/styles.css">
    <title>Web-Project with XML</title>
  </head>
  <body>

      <div class="enter">
          <div class="enter-screen">
              <div class="app-title">
                  <h1>Choose XML and Parser</h1>
              </div>

              <div class="enter-form">
                  <div class="control-group">
                      <form action="controller" enctype="multipart/form-data" method="post">
                          <input type="hidden" name="command" value="parse_command">
                          <input type="hidden" name="recordsPerPage" value="5"/>
                          <input type="file" name="file" class="login-field" id="login-name" accept=".xml">
                          <div class="radio">
                              <input class="rad" type="radio" name="parser" value="dom"/> DOM parser<br/>
                              <input class="rad" type="radio" name="parser" value="sax"/> SAX parser<br/>
                              <input class="rad" type="radio" name="parser" value="stax"/> StAX parser
                          </div>
                          <input type="submit" class="btn btn-primary btn-large btn-block" value="create table">
                      </form>
                  </div>

              </div>
          </div>
      </div>

  </body>
</html>

src/main/webapp/jsp/table.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>


<%@ page contentType="text/html;charset=UTF-8" language="java" %>

<html>
<head>
    <title>Devices</title>
    <link rel="stylesheet" href="../style/styles.css">
</head>
<body class="secbody">

    <div>
        <table align="center">
            <tr>
                <th rowspan="3">ID</th>
                <th rowspan="3">Name</th>
                <th rowspan="3">Origin</th>
                <th rowspan="3">Price</th>
                <th colspan="6">Type</th>
                <th rowspan="3">Critical</th>
            </tr>
            <tr>
                <th rowspan="2">Peripheral</th>
                <th rowspan="2">Power</th>
                <th rowspan="2">Ports</th>
                <th colspan="3">Hardware</th>
            </tr>
            <tr>
                <th>Keyboard</th>
                <th>Mouse</th>
                <th>Speakers</th>
            </tr>
            <c:forEach var="computer" items="${devices}" >
                <tr>
                    <td>${computer.id}</td>
                    <td>${computer.name}</td>
                    <td>${computer.origin}</td>
                    <td>${computer.price}</td>
                    <td>${computer.type.peripheral}</td>
                    <td>${computer.type.power}</td>
                    <td>
                        <c:forEach var="port" items="${computer.type.ports}">
                            <c:out value="${port.portName}"></c:out>
                        </c:forEach>
                    </td>
                    <td>${computer.type.hardware.hasKeyboard}</td>
                    <td>${computer.type.hardware.hasMouse}</td>
                    <td>${computer.type.hardware.hasSpeakers}</td>
                    <td>${computer.critical}</td>
                </tr>
            </c:forEach>
        </table>

        <br/>

        <table align="center" border="1" cellpadding="5" cellspacing="5">
            <tr>
                <c:forEach begin="1" end="${noOfPages}" var="i">
                    <c:choose>
                        <c:when test="${currentPage eq i}">
                            <td>${i}</td>
                        </c:when>
                        <c:otherwise>
                            <td>
                                <form action="controller" enctype="multipart/form-data" method="post">
                                    <input type="hidden" name="command" value="load_info_command"/>
                                    <input type="hidden" name="recordsPerPage" value="5"/>
                                    <input type="hidden" name="page" value="${i}"/>
                                    <input class="btnpage" type="submit" value="${i}"/>
                                </form>
                            </td>
                        </c:otherwise>
                    </c:choose>
                </c:forEach>
            </tr>
        </table>

        <a class="btnback" href="../index.jsp">home</a>

    </div>

</body>
</html>